# app/email_client.py
"""
SMTP email integration — generic relay (Workspace, M365, Exchange, Postfix).

Sends a multipart text+HTML alert when a feed is unhealthy. Uses stdlib
smtplib only (no extra deps). Credentials are NEVER read from config.yaml —
only from environment variables (preferred for Cloud Run / Secret Manager)
or variables.yaml.
"""
import logging
import os
import smtplib
import ssl
from datetime import datetime, timezone
from email.message import EmailMessage
from email.utils import formatdate, make_msgid

logger = logging.getLogger(__name__)

_VARIABLES_FILE = "variables.yaml"


def _load_email_secrets():
    """
    Resolve SMTP credentials with env vars taking precedence over variables.yaml.

    Order for each value:
        1. Environment variable (EMAIL_SMTP_USERNAME / EMAIL_SMTP_PASSWORD)
        2. variables.yaml (email_smtp_username / email_smtp_password)

    Username/password are kept out of the main config dict so they are never
    serialised into log lines or LLM prompts.
    """
    file_vars = {}
    if os.path.exists(_VARIABLES_FILE):
        try:
            import yaml
            with open(_VARIABLES_FILE, "r", encoding="utf-8") as f:
                file_vars = yaml.safe_load(f) or {}
        except Exception as e:
            logger.warning(f"  📧 [EMAIL] Could not read {_VARIABLES_FILE}: {e}")

    return {
        "username": os.environ.get("EMAIL_SMTP_USERNAME") or file_vars.get("email_smtp_username", ""),
        "password": os.environ.get("EMAIL_SMTP_PASSWORD") or file_vars.get("email_smtp_password", ""),
    }


def _extract_feed_state(feed_metadata):
    """Pull a (state, failure_msg, last_run) triple from feed metadata."""
    if not feed_metadata or "feed_state" not in feed_metadata:
        return "unknown", "", "—"
    fs = feed_metadata["feed_state"]
    state = fs.get("state", "unknown")
    raw = fs.get("raw_feed") or {}
    failure_msg = (
        raw.get("failureMsg")
        or raw.get("failureMessage")
        or (raw.get("lastError") or {}).get("message", "")
        or ""
    )
    last_run = fs.get("last_run", "—") or "—"
    return state, str(failure_msg), str(last_run)


def _build_text_body(feed_config, check_results, feed_metadata, was_restarted, llm_findings):
    """Plaintext alternative — readable in any mail client."""
    feed_name = feed_config.get("name", "—")
    state, failure_msg, last_run = _extract_feed_state(feed_metadata)
    now_iso = datetime.now(timezone.utc).isoformat()

    out = []
    out.append(f"Unhealthy feed detected: {feed_name}")
    out.append(f"Reported at: {now_iso} (UTC)")
    out.append("")
    out.append(f"Health check: {state}")
    out.append(f"Last ingested: {last_run}")
    out.append(f"Failure message: {failure_msg or '(none reported)'}")
    if was_restarted:
        out.append("Auto-restart attempted: yes (still unhealthy after retry)")
    out.append("")
    out.append("== Check results ==")
    if check_results:
        for name, (healthy, details) in check_results.items():
            status = "PASSED" if healthy else "FAILED"
            line = f"- {name}: {status}"
            if details:
                line += f" — {details}"
            out.append(line)
    else:
        out.append("(no checks recorded)")
    out.append("")
    out.append("== Suggested fix ==")
    out.append((llm_findings or "(LLM investigation not enabled or no findings produced)").strip())
    out.append("")
    out.append("Note: This suggestion was generated by AI and may be inaccurate. "
               "Please verify before taking action.")
    return "\n".join(out)


def _html_escape(s):
    """HTML-escape including quotes (defends against attribute-context breakouts)."""
    import html
    return html.escape(str(s), quote=True)


def _build_html_body(feed_config, check_results, feed_metadata, was_restarted, llm_findings):
    """Simple HTML alternative — inline styles, no external assets."""
    feed_name = feed_config.get("name", "—")
    state, failure_msg, last_run = _extract_feed_state(feed_metadata)
    now_iso = datetime.now(timezone.utc).isoformat()

    rows = []
    if check_results:
        for name, (healthy, details) in check_results.items():
            color = "#1a7f37" if healthy else "#cf222e"
            label = "PASSED" if healthy else "FAILED"
            rows.append(
                f"<li><strong>{_html_escape(name)}</strong>: "
                f"<span style='color:{color}'>{label}</span>"
                f"{' — ' + _html_escape(details) if details else ''}</li>"
            )
    else:
        rows.append("<li>(no checks recorded)</li>")

    llm_block = _html_escape(llm_findings or "(LLM investigation not enabled or no findings produced)") \
        .replace("\n", "<br>")
    restart_line = (
        "<p><strong>Auto-restart attempted:</strong> yes (still unhealthy after retry)</p>"
        if was_restarted else ""
    )

    return f"""<!doctype html>
<html><body style="font-family:-apple-system,Segoe UI,Helvetica,Arial,sans-serif;color:#1f2328;">
  <div style="border-left:4px solid #cf222e;padding:12px 16px;background:#fff8f8;">
    <h2 style="margin:0 0 8px 0;color:#cf222e;">Unhealthy Feed Detected</h2>
    <p style="margin:4px 0;"><strong>Feed:</strong> {_html_escape(feed_name)}</p>
    <p style="margin:4px 0;"><strong>Reported:</strong> {_html_escape(now_iso)} (UTC)</p>
    <p style="margin:4px 0;"><strong>Health check:</strong> {_html_escape(state)}</p>
    <p style="margin:4px 0;"><strong>Last ingested:</strong> {_html_escape(last_run)}</p>
    <p style="margin:4px 0;"><strong>Failure message:</strong> {_html_escape(failure_msg or '(none reported)')}</p>
    {restart_line}
  </div>
  <h3 style="margin-top:20px;">Check results</h3>
  <ul>{''.join(rows)}</ul>
  <div style="border-left:4px solid #1a7f37;padding:12px 16px;background:#f6fff8;margin-top:20px;">
    <h3 style="margin:0 0 8px 0;color:#1a7f37;">Suggested fix</h3>
    <div>{llm_block}</div>
    <p style="margin-top:12px;font-style:italic;color:#57606a;">
      Note: This suggestion was generated by AI and may be inaccurate.
      Please verify before taking action.
    </p>
  </div>
</body></html>"""


def send_email_alert(
    config,
    feed_config,
    check_results,
    feed_metadata=None,
    was_restarted=False,
    llm_findings=None,
):
    """
    Send an SMTP alert for an unhealthy feed. Returns True on success, False
    otherwise. Best-effort — never raises.
    """
    email_cfg = config.get("actions", {}).get("email", {}) or {}
    if not email_cfg.get("enabled", False):
        logger.info("  📧 [EMAIL] Disabled in config — skipping")
        return False

    # Non-sensitive transport settings come from config.yaml.
    smtp_server = email_cfg.get("smtp_server", "")
    smtp_port = int(email_cfg.get("smtp_port", 587))
    use_starttls = email_cfg.get("use_starttls", True)
    use_ssl = email_cfg.get("use_ssl", False)  # True for implicit TLS (port 465)
    from_address = email_cfg.get("from_address", "")
    recipients = email_cfg.get("recipients") or []
    timeout_seconds = int(email_cfg.get("timeout_seconds", 30))

    # Auth (optional — some internal relays accept unauthenticated mail
    # from allow-listed source IPs / VPC subnets).
    secrets = _load_email_secrets()
    username = secrets.get("username") or ""
    password = secrets.get("password") or ""

    # ── Refuse to send credentials over a non-encrypted channel. ──
    # If a username/password is configured but neither STARTTLS nor implicit
    # TLS is enabled, hard-fail rather than transmit auth in cleartext.
    if (username or password) and not (use_starttls or use_ssl):
        logger.error(
            "  📧 [EMAIL] SMTP credentials configured but TLS is disabled — "
            "refusing to send cleartext auth. Set use_starttls: true "
            "(or use_ssl: true for port 465)."
        )
        return False

    missing = [
        k for k, v in {
            "smtp_server": smtp_server,
            "from_address": from_address,
            "recipients": recipients,
        }.items() if not v
    ]
    if missing:
        logger.error(f"  📧 [EMAIL] Missing config: {', '.join(missing)} — skipping")
        return False

    # ── Build the message ──
    feed_name = feed_config.get("name", "unknown")
    subject = f"[Feed Health] Unhealthy feed: {feed_name}"

    msg = EmailMessage()
    msg["Subject"] = subject
    msg["From"] = from_address
    msg["To"] = ", ".join(recipients)
    msg["Date"] = formatdate(localtime=True)
    msg["Message-ID"] = make_msgid()
    # Auto-Submitted prevents auto-replies / out-of-office bounces from
    # cluttering the inbox during an incident.
    msg["Auto-Submitted"] = "auto-generated"

    text_body = _build_text_body(
        feed_config, check_results, feed_metadata, was_restarted, llm_findings
    )
    html_body = _build_html_body(
        feed_config, check_results, feed_metadata, was_restarted, llm_findings
    )
    msg.set_content(text_body)
    msg.add_alternative(html_body, subtype="html")

    # ── Send ──
    tls_context = ssl.create_default_context()
    try:
        if use_ssl:
            with smtplib.SMTP_SSL(
                smtp_server, smtp_port, timeout=timeout_seconds, context=tls_context
            ) as smtp:
                if username and password:
                    smtp.login(username, password)
                smtp.send_message(msg)
        else:
            with smtplib.SMTP(smtp_server, smtp_port, timeout=timeout_seconds) as smtp:
                smtp.ehlo()
                if use_starttls:
                    smtp.starttls(context=tls_context)
                    smtp.ehlo()
                if username and password:
                    smtp.login(username, password)
                smtp.send_message(msg)
    except (smtplib.SMTPException, OSError) as e:
        # Catch both SMTP-level errors and socket/timeout/TLS errors. Do NOT
        # log the exception's full string verbatim if it might echo back the
        # username — smtplib's errors do not include the password but can
        # include the rejected username on AUTH failures.
        logger.error(f"  📧 [EMAIL] Send failed for '{feed_name}': {type(e).__name__}: {e}")
        return False

    logger.warning(
        f"  📧 [EMAIL] Alert sent for '{feed_name}' to {len(recipients)} recipient(s)"
    )
    return True
